source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '9.0'

target 'Shop' do
    use_frameworks!
    inhibit_all_warnings!

    pod 'Texture', :path => '../..'

    target 'ShopTests' do
        inherit! :search_paths
        # Pods for testing
    end
end
