# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

source 'https://cdn.cocoapods.org/'
target 'Shop' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  # use_frameworks!

  # Pods for Shop

pod 'Texture'

  target 'ShopTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
