source 'https://cdn.cocoapods.org/'
platform :ios, '14.0'
target 'Sample' do
  pod 'Texture/IGListKit', :path => '../..'
  pod 'Texture/PINRemoteImage', :path => '../..'
  pod 'Texture/Yoga', :path => '../..'
  pod 'Texture/Video', :path => '../..'
  pod 'Weaver', :git => 'https://github.com/TextureGroup/Weaver.git', :branch => 'master'
end
